#!/bin/bash
#SBATCH -p nodes
#SBATCH --job-name=NickelatesFinal
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=7GB
#SBATCH --output=Slurm/final.txt

module purge ## this clears the modules loaded before to get a fresh start
module add anaconda3                   # modules to be loaded
python3 Final_Itteration.py --n_threads $SLURM_CPUS_PER_TASK
