#!/bin/bash
#PBS -A st-anocera-1
#PBS -N RNiO3 
#PBS -l walltime=12:00:00,select=1:ncpus=32:mem=128gb
#PBS -o PBS/out_^array_index^.txt
#PBS -e PBS/err_^array_index^.txt
#PBS -J 0-242

cd $PBS_O_WORKDIR
source ../.venvs/HFA/bin/activate
python trials.py --run_ind $PBS_ARRAY_INDEX --n_threads 32 
