#!/bin/bash
#PBS -A st-anocera-1
#PBS -N RNiO3
#PBS -l walltime=1:30:00,select=1:ncpus=32:mem=12gb
#PBS -o PBS/out_^array_index^.txt
#PBS -e PBS/err_^array_index^.txt
#PBS -J 0-825

cd $PBS_O_WORKDIR
source ../.venvs/HFA/bin/activate
python Diagrams.py --run_ind $PBS_ARRAY_INDEX --n_threads 32 
