#!/bin/bash
#PBS -A st-anocera-1
#PBS -q nodes
#PBS -N NickelatesTrials
#PBS -l nodes=1:ppn=32
#PBS -l mem=187GB
#PBS -o Results/logs/Trial-%a.txt
#PBS -t 0-5 							#Job array

#mkdir -p Results/logs
module purge ## this clears the modules loaded before to get a fresh start
module add anaconda3                   # modules to be loaded
python3 trials.py --trial_ind $PBS_ARRAYID --n_threads $PBS_NUM_PPN
