#!/bin/bash
#SBATCH -p nodes
#SBATCH --job-name=NickelatesTrial
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=7GB
#SBATCH --array=0-5
#SBATCH --error=Slurm/error-%A-%a.txt
#SBATCH --output=Slurm/%A-%a.txt

module purge
module add anaconda3
python3 trials.py --trial_ind $SLURM_ARRAY_TASK_ID --n_threads $SLURM_CPUS_PER_TASK
